# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/../private/google-modules/display
ccflags-y += -I$(srctree)/../private/google-modules/display/samsung/include/uapi
ccflags-y += -I$(srctree)/../private/google-modules/touch/common
ccflags-y += -I$(srctree)/../private/google-modules/touch/common/include

obj-$(CONFIG_TOUCHSCREEN_FTS)	+= ftm5.o
ftm5-objs = fts.o fts_proc.o
ftm5-objs += \
	fts_lib/ftsCompensation.o fts_lib/ftsCore.o fts_lib/ftsError.o \
	fts_lib/ftsFrame.o fts_lib/ftsIO.o fts_lib/ftsTest.o fts_lib/ftsTime.o \
	fts_lib/ftsTool.o fts_lib/ftsFlash.o fts_lib/ftsGesture.o

