# SPDX-License-Identifier: GPL-2.0
# Pixel UFSHCD Makefile

obj-$(CONFIG_SCSI_UFS_EXYNOS_GS) += ufs-exynos-gs.o
ufs-exynos-gs-y += ufs-exynos.o ufs-pixel.o
ufs-exynos-gs-$(CONFIG_SOC_GS101) += gs101/ufs-cal-if.o
ufs-exynos-gs-$(CONFIG_SOC_GS201) += gs201/ufs-cal-if.o
ufs-exynos-gs-$(CONFIG_SOC_ZUMA) += zuma/ufs-cal-if.o
ufs-exynos-gs-$(CONFIG_SCSI_UFS_CRYPTO) += ufs-pixel-crypto.o

ccflags-y += -I $(srctree)/drivers/ufs

obj-$(CONFIG_SCSI_UFS_PIXEL_FIPS140) += ufs-pixel-fips140.o
ufs-pixel-fips140-y += ufs-pixel-fips.o ufs-pixel-fips_sha256.o \
		       ufs-pixel-fips140-refs.o
# Use -DBUILD_FIPS140_KO to disable dynamic code patching as that would
# invalidate the hash of the module's .text section
CFLAGS_ufs-pixel-fips140.o += -DBUILD_FIPS140_KO
CFLAGS_ufs-pixel-fips_sha256.o := -DBUILD_FIPS140_KO
hostprogs := ufs-pixel-fips_gen_hmac
HOSTLDLIBS_ufs-pixel-fips_gen_hmac := -lcrypto -lelf
$(obj)/ufs-pixel-fips140.o: $(obj)/ufs-pixel-fips_gen_hmac
