subdir-ccflags-y += -I$(srctree)/$(src)/../common/
subdir-ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/
subdir-ccflags-y += -DS2MPU_V9

obj-m += pkvm-s2mpu-v9.o

$(obj)/../common/hyp/kvm_nvhe.o: FORCE
		$(Q)$(MAKE) $(build)=$(obj)/../common/hyp $(obj)/../common/hyp/kvm_nvhe.o

clean-files := hyp/hyp.lds hyp/hyp-reloc.S

pkvm-s2mpu-v9-y := ../common/pkvm_s2mpu.o \
		   ../common/s2mpu.o \
		   ../common/exports.o \
		   pkvm-s2mpu-faults-v9.o

pkvm-s2mpu-v9-$(CONFIG_MODULES) += ../common/hyp/kvm_nvhe.o